services:
  app1:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    command: streamlit run dealabs-scraper/main.py --server.port=8501 --server.address=0.0.0.0

  app2:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    command: streamlit run dealabs-scraper/main.py --server.port=8502 --server.address=0.0.0.0

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
