version: '3.7'

services:
  app1:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    environment:
      - server.port=8501
      - server.address=0.0.0.0

  app2:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    environment:
      - server.port=8501
      - server.address=0.0.0.0

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
